# Generated by Django 3.1.3 on 2021-05-10 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('major_version', models.PositiveSmallIntegerField()),
                ('minor_version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('build_maintenance_version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('revision_build_version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BrowserFeature',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='IpAddressType',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformanceEntryType',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('opt_out_tracking', models.BooleanField(default=False)),
                ('opt_out_event_tracking', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ReferrerType',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_ajax', models.BooleanField()),
                ('requested_at', models.DateTimeField()),
                ('browser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.browser')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.device')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.ipaddress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestHeaderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestHeaderValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('value', models.CharField(max_length=250)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.requestheader')),
            ],
            options={
                'unique_together': {('header', 'value')},
            },
        ),
        migrations.CreateModel(
            name='RequestMethod',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.URLField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UrlParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UrlParameterValue',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.urlparameter')),
            ],
            options={
                'unique_together': {('parameter', 'value')},
            },
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('value', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UrlParameterValues',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parameter_value', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.urlparametervalue')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_request_at', models.DateTimeField()),
                ('last_request_at', models.DateTimeField()),
                ('requests', models.ManyToManyField(to='django_web_analytics.Request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestHeaderValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('header_value', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.requestheadervalue')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='requestheader',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.requestheadertype'),
        ),
        migrations.AddField(
            model_name='request',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.requestmethod'),
        ),
        migrations.AddField(
            model_name='request',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.referrer'),
        ),
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.requesttype'),
        ),
        migrations.AddField(
            model_name='request',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.url'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='user_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.useragent'),
        ),
        migrations.AddField(
            model_name='referrer',
            name='referrer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.referrertype'),
        ),
        migrations.CreateModel(
            name='PerformanceEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('start_time', models.FloatField()),
                ('duration', models.FloatField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_web_analytics.performanceentrytype')),
            ],
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='ip_address_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.ipaddresstype'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.devicetype'),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.manufacturer'),
        ),
        migrations.CreateModel(
            name='RequestFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('supported', models.BooleanField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.browserfeature')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.request')),
            ],
            options={
                'unique_together': {('request', 'feature')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='referrer',
            unique_together={('referrer_type', 'value')},
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=25)),
                ('major_version', models.PositiveIntegerField(blank=True, null=True)),
                ('minor_version', models.PositiveIntegerField(blank=True, null=True)),
                ('build_maintenance_version', models.PositiveIntegerField(blank=True, null=True)),
                ('revision_build_version', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.manufacturer')),
            ],
            options={
                'unique_together': {('manufacturer', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together={('ip_address_type', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('device_type', 'manufacturer', 'name')},
        ),
        migrations.CreateModel(
            name='BrowserFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('supported', models.BooleanField()),
                ('analytics_browser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.browser')),
                ('analytics_browser_feature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_web_analytics.browserfeature')),
            ],
            options={
                'unique_together': {('analytics_browser', 'analytics_browser_feature')},
            },
        ),
    ]
