# Generated by Django 2.2.9 on 2020-01-12 18:52

from django.db import migrations
import django_web_analytics


class Migration(migrations.Migration):

    dependencies = [
        ('django_web_analytics', '0001_initial'),
    ]

    def create_request_types(apps, schema_editor):
        request_types = ['HTTP', 'HTTPS', 'GRPC']
        for name in request_types:
            if not django_web_analytics.models.RequestType.objects.filter(name=name).exists():
                django_web_analytics.models.RequestType.objects.create(name=name, description='')

    def create_header_types(apps, schema_editor):
        types = ['Authentication', 'Caching', 'Client Hints', 'Conditionals', 'Connection Management', 'Content Negotiation', 'Controls', 'Cookies', 'CORS', 'Do Not Track', 'Downloads', 'Message Body Information', 'Proxies', 'Redirects', 'Request Context', 'Response Context', 'Range Requests', 'Security', 'Server-Sent Events', 'Transfer Coding', 'Websockets', 'Other']
        for name in types:
            if not django_web_analytics.models.RequestHeaderType.objects.filter(name=name).exists():
                django_web_analytics.models.RequestHeaderType.objects.create(name=name)

    def create_methods(apps, schema_editor):
        methods = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'CONNECT', 'OPTIONS', 'TRACE']
        for method in methods:
            if not django_web_analytics.models.RequestMethod.objects.filter(name=method).exists():
                django_web_analytics.models.RequestMethod.objects.create(name=method, description='')

    def create_ip_address_types(apps, schema_editor):
        types = ['IPv4', 'IPv6', 'Invalid']
        for name in types:
            if not django_web_analytics.models.IpAddressType.objects.filter(name=name).exists():
                django_web_analytics.models.IpAddressType.objects.create(name=name, description='')

    def create_device_types(apps, schema_editor):
        types = ['PC', 'Tablet', 'Mobile', 'TV', 'Bot']
        for name in types:
            if not django_web_analytics.models.DeviceType.objects.filter(name=name).exists():
                django_web_analytics.models.DeviceType.objects.create(name=name, description='')

    operations = [
        migrations.RunPython(create_request_types),
        migrations.RunPython(create_header_types),
        migrations.RunPython(create_methods),
        migrations.RunPython(create_ip_address_types),
        migrations.RunPython(create_device_types),
    ]
